"""Dependency-free demonstration browser chat interface."""
from fastapi.responses import HTMLResponse

CHAT_PAGE = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Banking Agentic Chat</title><style>body{font:16px system-ui;max-width:760px;margin:2rem auto;padding:0 1rem;background:#f7f9fc}input,button{padding:.7rem;margin:.2rem;width:100%;box-sizing:border-box}button{background:#0656b9;color:white;border:0;border-radius:4px;cursor:pointer}.message{padding:.7rem;margin:.5rem 0;border-radius:6px;background:white}.assistant{border-left:4px solid #0656b9}.error{color:#a40000}#chat{margin-top:1rem}</style></head><body><h1>Banking Agentic Chat</h1><p>Demo UI: use a bank-issued bearer token. Do not enter account numbers, passwords, or one-time codes.</p><input id="token" type="password" placeholder="Bearer token"><input id="session" value="browser-demo" placeholder="Session ID"><input id="message" placeholder="Ask about balance, transactions, statements, address, cheque book, or KYC"><button id="send">Send</button><div id="chat" aria-live="polite"></div><script>const out=document.querySelector('#chat');const add=(text,kind='')=>{const e=document.createElement('div');e.className='message '+kind;e.textContent=text;out.append(e)};document.querySelector('#send').onclick=async()=>{const m=document.querySelector('#message');if(!m.value.trim())return;add('You: '+m.value);try{const r=await fetch('/v1/chat',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+document.querySelector('#token').value},body:JSON.stringify({session_id:document.querySelector('#session').value,message:m.value})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Request failed');add('Assistant: '+data.response,'assistant');m.value=''}catch(e){add(e.message,'error')}};</script></body></html>"""


def chat_page() -> HTMLResponse:
    """Return a simple same-origin interface suitable for development demonstrations."""
    return HTMLResponse(CHAT_PAGE)
